name: Python tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Prevent sending test emails
        run: |
          echo "RUN_RESEND_TEST=0" >> $GITHUB_ENV
      - name: Run pytest
        run: |
          python -m pytest -q
        env:
          # Provide minimal safe defaults so tests don't rely on secrets
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          RECIPIENT: dshodge2020@outlook.com
          FROM_EMAIL: dshodge2020@outlook.com
